name: shared_common
description: Shared common package.
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  freezed_annotation: ^3.1.0

dev_dependencies:
  test: ^1.26.3
  lint: ^2.8.0
  freezed: ^3.2.0
  build_runner: ^2.6.0