name: shared_util
description: Shared utility package.
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  logger: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0