name: search_favorites

packages:
  - packages/**


ide:
  intellij: true

scripts:
  get:
    run: melos exec -- "flutter pub get"
  analyze:
    run: melos exec -- "flutter analyze"
  test:
    run: melos exec -- "flutter test"
  build:
    run: melos exec -- "flutter pub run build_runner build --delete-conflicting-outputs"
  clean:
    run: melos exec -- "flutter clean"