name: feature_search
description: Search feature package.
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^3.0.0-dev.17
  riverpod_annotation: ^3.0.0-dev.17
  # core packages
  core_designsystem:
    path: ../../core/designsystem
  core_domain:
    path: ../../core/domain
  core_data:
    path: ../../core/data
  # shared packages
  shared_ui:
    path: ../../shared/ui
  shared_util:
    path: ../../shared/util
  router:
    path: ../../router
  shared_common:
    path: ../../shared/common
  home_widget: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^3.0.0-dev.17
  freezed: ^3.2.0
  build_runner: ^2.6.0